### ISSUE TITLE
Expand git support to infer addon name

### ISSUE THREAD

**Issue by WanderingFox** [WowUp/WowUp#1060]
**Is your feature request related to a problem? Please describe.**
Currently git based addon updating requires that an appropriate zip be packaged with the repository, but often times only the default (source) zip is present.

**Describe the solution you'd like**
The default release zip file is almost identical to the zip file wowup expects, except for the lack of a properly named root directory. It'd be amazing to either infer this from the toc files or allow manual entry in the case where it cannot be inferred. This would greatly expand the number of addon repositories wowup supports without being dependent on addon authors making changes.

In other words:
Expand support to any repository where the release zip contains a single folder, regardless of name, where a .toc file exists inside by renaming the folder to the addon name.

**Describe alternatives you've considered**
The only alternative is to use other aggregation links (wowinterface, curse, etc) or getting addon authors to package an additional zip with slightly altered structure.

**Additional context**
As an example, Details! won't install via github url because there is no zip with a "Details" root folder, but there are releases with source zips. The only transformation that would need to happen is reading the toc filename to determine the root folder should be named "Details" instead of "Details-Damage-Meter-DetailsRetail..."

**Comment by Duckwhale** [comment]
This won't work if the addon is relying on the CurseForge packager, e.g., to substitute localization phrases. Since the release zip's provided by GitHub are only snapshots of the repository at a given commit, none of these would be resolved.

In the case of Details, you can observe the effect by checking any of the localization files inside the zip. They don't contain the actual translations until CurseForge has processed them and created a proper release on their website.

If you attempt to load this incomplete version ingame you'll get lots of errors at best, though most likely it won't function at all.

**Comment by jliddev** [comment]
This is not really feasible in many cases, certain components of the addon need to be compiled however the author has it setup. We support any old zip file with standard folder structure, which is easily done with the 'standard' [bigwigs packager](https://github.com/BigWigsMods/packager).

**Comment by WanderingFox** [comment]
That's unfortunate... but understandable. Thank you for taking time to look into it!
