### ISSUE TITLE
Unable to connect to Wago.io

### ISSUE THREAD

**Issue by FakeGodz** [WowUp/WowUp#1246]
I am trying to download addons from Wago now that curseforge doesn't work (also some github link doesn't work)

I can go to Wago website like usual, and download addon (and weakauras) directly from there.

But for whatever reason, WoWUp can't connect to it. 

It simply said "Error contacting Wago" and the ads on bottom left doesn't show up, even though the gigantic box is there, it's just black.

![image](https://user-images.githubusercontent.com/87436803/168798546-d3e1a348-5270-46f6-b354-eb9afe496ac9.png)

Firewall is off and everything, i mean it can connect to github and used to able to curseforge normally. Dunno why it just refuses to connec to Wago.

**Comment by linaori** [comment]
Do you have a pihole or anything else to block ad traffic? If so, there's a list on Discord you can use to allow Wago to get an API key

**Comment by JCMarques15** [comment]
Hi @linaori, I am also having the same issue, and indeed like you mentioned I run a PiHole! I was wondering if you could provide a bit more info about this list on Discord, if possible a link towards it as I seem to be unable to find it.

**Comment by JCMarques15** [comment]
> This is the link to the message: https://discord.com/channels/730098865717379122/761739154026397744/943195768523726890

Thank you very much :-)

**Comment by Sinvoll** [comment]
Was this issue resolved? I am having the same problem.

**Comment by Silun** [comment]
I have also never seen it work. Even when I do not use any kind of DNS filtering. Does not work with either 1.1.1.1 or 8.8.8.8. I do see ads on wago.io but not in WowUp. The above discord link does not work, I just see this:

![image](https://user-images.githubusercontent.com/17919060/183562379-2b645e26-19a4-4e03-b69a-5d0403550449.png)

**Comment by wUEZRs** [comment]
Same problem, and the addons that use Wago as a source do not update

<img width="448" alt="Image" src="https://github.com/user-attachments/assets/f510bc91-d80b-468c-9769-dc16c3be392c" />

Unless Google Play is somewhat involved, I see nothing in any network logs that would indicate a block either.

I also use the Wago access key to no avail.

Since Curseforge seems to be on good terms with WoWup again I will try that beta version instead. It's a shame because in theory this had everything I needed, if Wago worked.
