### ISSUE TITLE
Support modified addons

### ISSUE THREAD

**Issue by syndenbock** [WowUp/WowUp#197]
I have a few addons that have local modifications to support the latest patch of WoW.
These do not show up in WoWUp which is a shame, because I would like to update them to an official version as soon as an update is available.
So it would be great if addons without a detected source would be displayed anyways and if we could manually set a source like selecting "Curseforge", "WoWInterface" or "Github" and/or or even setting specific source links for them.

**Comment by MaxMcBurn** [comment]
+1

**Comment by skmzarn** [comment]
I remember that Curse/Twitch/Overwolf blabla shitty thing - I don't know what it's called nowadays - whatever - had this working. Whenever you modified anything in an addon that was in your addon-list, its version was changed to "Modified", which made sense, and was really handy. I don't remember what happened to that feature.

**Comment by teelolws** [comment]
The reason it doesn't is so it doesn't throw away the changes you've made to the addon.

**Comment by panoplybez** [comment]
This explains why a bunch of my addons don't show in the list - because they might have been abandoned and I had to hand modify them to get them working again. However, IF an author ever came back and updated them officially, would we know? Would wowup start showing them in the list?  My main concern isn't that they are hidden when modified per say, but that we won't know about future official updates because they don't show. Could wowup show them, but then we users select 'Ignore' if we know they are modified?

**Comment by Walkerbo** [comment]
I would assume that it would operate the same as an ignored addon, it would not update but it should still show the local version and the remote version, and a column for last updated date.

**Comment by strayge** [comment]
Would be perfect to shown not just `Modified`, but also original version of modified addon.  
It's useful for knowing if it really needed to be updated.

Modified addons should be excluded from `Update All`, but still has button for force update (possibly with warning dialog).

**Comment by jliddev** [comment]
lump this in with #71

**Comment by jliddev** [comment]
I misunderstood this one. We need to have some thought put into this to play nice with re-scanning once modified.

**Comment by cremor** [comment]
@jliddev Should this be fixed? Because I just tried the following with v2.4.0-beta.10:

1. Install an addon from Curse
2. Modify a file of the addon
3. Re-scan the folder

After that the addon was set to ignored and the provider was "unkown". I'd at least have expected it to keep the provider.

**Comment by linaori** [comment]
The provider information is lost on rescan because it can't be matched anymore

**Comment by cremor** [comment]
Yeah ok, but how should that work then? I thought that keeping the provider is what @jliddev meant with "play nice with re-scanning once modified" in his last comment.

**Comment by strayge** [comment]
@cremor for now WowUp do not support modified addons at all.  

Workaround: 
1. disable auto-updates for modded addons
2. reapply modifications after each manual update (i put all my modifications into [python script](https://gist.github.com/strayge/755cad67a68a00a98fc7b99a1a90de54))
3. do not ever press rescan button

**Comment by cremor** [comment]
Yes, but that was already the case before. So why was this issue closed?
Or was it a "won't fix" type of close?

If this was fixed, I'd expect WowUp to
* Detect modified addons (without a re-scan)
* Prevent automatic updates of modified addons
* Exclude modified addons from "update all"
* Request an explicit confirmation from the user if he updates a single modified addon
* Retains the connection to the provider for modified addon on re-scan

**Comment by linaori** [comment]
> Yes, but that was already the case before. So why was this issue closed?

Not sure why the issue was closed, but as I mentioned before, doing a rescan will simply toss the known information and try to guess which addon it is. I'm not sure if this is a "won't fix", but due to how the process work it's hard to implement, because:

> Detect modified addons (without a re-scan)

This is not something we can do right now. It's possible though, so if someone is willing to build that, we can look into how it should be done.

> Prevent automatic updates of modified addons
> Exclude modified addons from "update all"
> Request an explicit confirmation from the user if he updates a single modified addon

This part is easy if the above part is solved.

> Retains the connection to the provider for modified addon on re-scan

I don't think this will be possible for the aforementioned reasons

**Comment by jliddev** [comment]
To detect a "modified" folder is not a light operation. The reason we do not actively scan every file in every addon folder is simply for speed. This is not a use case for most users. 

What you're asking for is to essentially perform a scan every single time you check for updates which is not viable.

**Comment by cremor** [comment]
@jliddev Understandable, thanks for the information.

What do you think about it if WowUp would only detect modified addons during a re-scan?
Yes, @linaori explained that this isn't possible right now. But I assume this could be changed so that not all information about addons is discarded? (Actually even right now not all information is discarded, e.g. the selected update channel is remembered.)
