### ISSUE TITLE
[2.x] Dynamic strings for Portuguese not being translated properly

### ISSUE THREAD

**Issue by sampaiodias** [WowUp/WowUp#338]
Some dynamic strings for portuguese (the ones found on the pt.json file within curly braces) are currently bugged. For example, on the "released at" column, the text "5 days ago":
- on the "Released at" column, there's the text "5 days ago";
- that should be translated to "5 dias atrás" ('dias' = 'days' in portuguese);
- that's currently being translated as "5 days atrás".

However, that's not consistent. Another example:
- on the "Downloads" column, there's the text "15 million";
- that should be translated to "15 milhões" (plural);
- and it is currently being translated to "15 milhão".

Ignoring the fact that the app got the plural translation wrong, both strings on pt.json are formatted the same way ("{count}" and "{day} {days}"). Is it a bug? And just to confirm, should we translate or modify the content inside curly braces?

**Comment by mrchops1024** [comment]
The text inside the curly braces is the translation for that group. So for example, when the count = 1, it will use the word inside the curly brace for the 'one' group. Otherwise it will use the one for other. I can see that the translation wasn't fully completed.

For example, DAYS_AGO should probably be: `"{count} {count, plural, one{dia} other{dias}} atrás"`

I see quite a few issues in the pt.json file. Unfortunately I don't speak the language so I'm not able to fix all the issues, but we welcome PRs if you want to give it a shot.

If you paste the existing strings (such as the one I specified above) into the following website, you can set the language and count and see what the output will be (see example):

![video_2020-11-04 18-44-37](https://user-images.githubusercontent.com/7883662/98191354-dbd17b80-1ecd-11eb-8c43-16e17b7e4d42.gif)

Here's the site: https://format-message.github.io/icu-message-format-for-translators/editor.html

**Comment by sampaiodias** [comment]
@mrchops1024 thanks for the info, I'll fix it later
