### ISSUE TITLE
Add changelog of addon

### ISSUE THREAD

**Issue by Cratis1831** [WowUp/WowUp#54]
add a feature where you click on an addon you can see the changelog notes or maybe just put a url link to point to changelog page if there is one, like point to that addons changelog url on curse or whatever provider

Perhaps in the interim under the addon name can be link that points to the CF changelog link, until a permanent feature is added

**Comment by asotoudeh18** [comment]
Perhaps in the interim under the addon name can be link that points to the CF changelog link, until a permanent feature is added

**Comment by Daeveren** [comment]
@jliddev I see this being tagged as 2.1 - I've installed 2.1 beta today and I can't see how to find the update notes of an addon. Please, let us see the addon's changelog easy, while clicking on an addon in the list (as it was working in the old Curse then Twitch app for years) or alternatively by having a view changelog link or small button next to each addon in the list. Alternatively, add an option so that the popup which opens when you click an addon will instead display the changelog by default instead of the addon's description (who ever needs to see an addon's main description when they already have the addon installed?)

Pre 2.0, viewing the changelog was achievable by clicking on the addon's name which then would open the addon's page on curseforge/wowinterface in the browser, where the user could then click further to read the changelog; but with 2.0, this has been buried in another popup/additional click, making it harder than ever to access the changelog.

I cannot wait for this feature to be added, since it's the absolutely main feature I'm missing from WowUp. My daily usage for addons is: read their changelog > update addon > repeat for the next addons. 

Thank you for your hard work and can't wait to see it in the beta!

**Comment by Knaledge** [comment]
What is the current roadmap for this feature? Are there any hurdles that might benefit from contribution?

**Comment by Daeveren** [comment]
Just seen this in the lastest beta (2.1.0 beta 8), this is fabulous news! Thank you, @jliddev 
A somewhat logical suggestion here would be to add a toggle in the Options to let the user chose the default tab shown when clicking on an addon's name. The argument/reason here is that, for the addons that the user already installed, the user will never need to read the addon's description, but if any, it would eventually want to read the latest update changelog.

**Comment by jliddev** [comment]
@Daeveren This should work in beta 13

**Comment by Daeveren** [comment]
> Addon details dialog will remember which tab you last selected.

Confirming it's working in beta 13. Man, this is so awesome! Thank you so much for your continuous efforts of making WowUp better and listening for our voice.
/respect
