### ISSUE TITLE
[Feature] Supporting the other areas of CurseForge (MC, KSP, etc)

### ISSUE THREAD

**Issue by CDAGaming** [WowUp/WowUp#560]
**Is your feature request related to a problem? Please describe.**
While I'm aware that WowUp is specifically meant for World of Warcraft, I'd personally see a lot of benefits if this were to become more of a full-scale app to support the other marketplaces curseforge supports, such as Minecraft, KSP, and so forth. I feel that the UI has been very simplistic to use for myself and no doubt many others, and could benefit from being able to support a wider audience, if the time allots of course.

**Describe the solution you'd like**
Expanding the scope of the app, either here or as a separate project, to allow eventual support for MC Mods, KSP addons, modpacks, etc.

**Comment by jliddev** [comment]
I am happy to facilitate this, we have a decently flexible pattern, but would need someone to actually do the dev work besides me, as i am only 1 person :P

**Comment by mnejing** [comment]
My absolutely unrequested 2 cents says that's kind of a bad direction. Every time an app starts supporting more and more games, it just ends up getting bought up because of an offer too good to pass up, and it turns in to Overwolf, Curse Client, or the Twitch App. Then what? It always ends up becoming some bloated ad delivery device.

**Comment by ShaunaGordon** [comment]
> My absolutely unrequested 2 cents says that's kind of a bad direction. Every time an app starts supporting more and more games, it just ends up getting bought up because of an offer too good to pass up, and it turns in to Overwolf, Curse Client, or the Twitch App. Then what? It always ends up becoming some bloated ad delivery device.

I agree with this. 

If the framework is flexible enough, what about "plugins" to the WowUp client itself? It would allow for decentralizing both the production/maintenance, and the features as a whole. There's still the issue of the core being too juicy of a target for a company to try to purchase, but its full value is greatly diluted across multiple groups.

**Comment by jliddev** [comment]
Seems odd to argue against improving a platform due to being too popular lol. We would need to get more dev power with knowledge about these other games/apps

**Comment by ShaunaGordon** [comment]
> Seems odd to argue against improving a platform due to being too popular lol.

Well, I guess the question is: how many millions of dollars are you willing to turn down? 😉 

> We would need to get more dev power with knowledge about these other games/apps

But seriously, though, I think a modular way would be good, if not for the "getting bought up by giants" matter, than for the "need more dev power" and clutter aspects. By allowing for modules, you wouldn't need the core WowUp team to maintain whatever games that are out there and whatever is needed to support them and whoever wanted to build that module wouldn't need particularly direct access to the WowUp core.

A quick use-case for the clutter part -- WoW is the only game I mod heavily via Curse (and now WowUp). I don't heavily mod games in general and the couple others that I do have their own systems. As a result, I don't need the massive selection like what the old Curse client had (and in fact, it felt bloated as all hell because of it). One of the things that I like about WowUp is that, because it's only WoW, it's super fast for me to hop in, update everything (or find what I need) and be done. 

I could see this being the case for people who play other games, too. Not everyone mods every game they own, and not everyone plays all of the heavily-moddable games, so it would make sense for them to have the option to only have the game(s) they care about in their mod manager.

It could also allow people to write their own modules for whatever obscure game that no one's ever heard of if they wanted to, instead of having to beg you to support it.
