### ISSUE TITLE
Support for AddOns hosted at Townlong Yak

### ISSUE THREAD

**Issue by NielsHeltner** [WowUp/WowUp#620]
**Is your feature request related to a problem? Please describe.**
Not per se. WowUp does not currently supported managing AddOns hosted at Townlong Yak (https://www.townlong-yak.com/addons/latest).

**Describe the solution you'd like**
I would like to be able to use WowUp to manage AddOns hosted at Townlong Yak (https://www.townlong-yak.com/addons/latest).

**Describe alternatives you've considered**
Convince the AddOn author of the AddOns hosted at Townlong Yak to publish them on GitHub or WowInterface.

**Additional context**
_None_

**Comment by jliddev** [comment]
We reached out to the author, he was not interested. That's about all we can do.

**Comment by CDAGaming** [comment]
I severly dislike authors who only want to support themselves. Thats the very kind of behavior that makes others rehost addons to get their way.

**Comment by NielsHeltner** [comment]
@CDAGaming I really do not think comments like that are warranted, especially given the author's reasoning for not wanting to have their addons hosted at CurseForge.

**Comment by cremor** [comment]
> We reached out to the author, he was not interested. That's about all we can do.

Not interested in a provider in WowUp or not interested in hosting his addons somewhere else? Or both?

**Comment by dadec666** [comment]
> @CDAGaming I really do not think comments like that are warranted, especially given the author's reasoning for not wanting to have their addons hosted at CurseForge.

The author just wants to promote his site, and about CurseForge he just has to justify.

**Comment by CDAGaming** [comment]
> @CDAGaming I really do not think comments like that are warranted, especially given the author's reasoning for not wanting to have their addons hosted at CurseForge.

Curseforge was not my concern, I couldnt give a second thought if they didnt want to host their mods elsewhere  My main concern is that if they are going to only have it on their site, the least they could do is at least enable things like wowup to support the site, which in the end would have given more of a user base since they are good addo s.

**Comment by duckies** [comment]
The page the author of Townlong links to talks about moving forward with addon hosting in general and his positions are fair.

- Development takes considerable effort and they were dissuaded by the poor experience interacting with users and lack of a clear monetization scheme.
- Github does not adequately connect non-technical users.
- If every addon author switched to Github we'd still need a service like CurseForge to reference and validate each repository, circling back to the issue.
- Letting an addon updater scrape your website is a strain on resources they likely do not want to deal with at this time.

It has not been long since the transition off of CurseForge, so I'm not sure what the negativity directed towards them is for. Just let them figure things out like they said they would.

**Comment by rahul0705** [comment]
I just want to point out CurseBreaker (https://github.com/AcidWeb/CurseBreaker) has just added support for townlong-yak would this change anything on WowUp's approach?

**Comment by CDAGaming** [comment]
Seems to check out, +1 for implementing this to WowUp

**Comment by jliddev** [comment]
We added support for this last night, it's currently in testing :)
![image](https://user-images.githubusercontent.com/20467484/105074130-95f86e00-5a4d-11eb-9707-54fff0885c46.png)

**Comment by ofbeaton** [comment]
It seems to me that auto updaters are at odds with addon authors who want users to go to their website and see their announcements, paypal/patron links, website ads. I think an author wanting their users to have to go to their website to download the addon they wrote is reasonable, even if it's more work for the user and may be a worse user experience. That may detract people from using the addon, but that's the authors choice.

I don't see CurseBreaker adding support without the authors approval as approval for wowup to do the same.

The only way I could see this working with the authors approval is:
* WowUp merely lists the addon and when a new version is out the "Install" button opens their browser to the addon author website.
* WowUp Desktop App or a WowUp Browser Addon adds a "Install with WowUp" link on supported websites, like the author's website so that users on the addon authors website can still easily install the addon into WowUp. This is a lot of work to support a worse experience, but does improve things for authors who still want to retain their websites.

In the end I think the control here belongs to the author addon. Yak addons are not the only ones, WoW-Pro for example only distributes their leveling addon via auto-updators/curse, and wants people to go to their website to download the other guide addons, from what I gather for similar reasons.

**Comment by linaori** [comment]
> Did Yak add an api then?
Yes, they added a public API

> Even if they did, I think it's important to discuss this situation in general, as author addons want you to go to their website, like WoW-Pro.
In case of a public API there's no need for this. In the scenario of Townlong Yak it was due to leaving curse, you can read the post why here: https://www.townlong-yak.com/box/goodbye-curseforge

When an addon is available through hub, donation links will be added in WowUp (see beta). There are other thoughts floating around how to support addons developers, so if you have ideas that are not intrusive to end-users you can always propose them.

> WowUp merely lists the addon and when a new version is out the "Install" button opens their browser to the addon author website.
That would hurt the end-users way more than it would benefit the addon developer.

> In the end I think the control here belongs to the author addon. Yak addons are not the only ones, WoW-Pro for example only distributes their leveling addon via auto-updators/curse, and wants people to go to their website to download the other guide addons, from what I gather for similar reasons.

I always thought that addon authors wanted their users to enjoy using the addon. When they actively work against addon users by limiting availability, putting it behind paywalls, or purposely making it impossible for addon managers to download it, they are only hurting their users.

**Comment by jliddev** [comment]
This is complete.
