### ISSUE TITLE
Provider channel shows long enum name after folder rescan

### ISSUE THREAD

**Issue by cremor** [WowUp/WowUp#647]
**Describe the bug**
After running "rescan folder" all my addons installed from Curse show `COMMON.ENUM.ADDON_CHANNEL_TYPE.undefined` in the "provider channel" column.

**To Reproduce**
1. Update to v2.1.0-beta.15
2. Click on 'rescan folder'
3. Check the table of installed addons

**Expected behavior**
The "provider channel" should show the same values as before the rescan action.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 84.0.1 (why is this relevant?)
 - Version v2.1.0.beta-15

**Comment by jliddev** [comment]
Added logic to avoid displaying this and display error text instead.

![image](https://user-images.githubusercontent.com/20467484/103471367-2b54ec00-4d45-11eb-9df0-04ebc82af7dd.png)

Also fix the root cause of this happening after a rescan

![image](https://user-images.githubusercontent.com/20467484/103471395-6fe08780-4d45-11eb-9812-1d1da43b60f9.png)
