### ISSUE TITLE
Search is not showing top downloaded results first

### ISSUE THREAD

**Issue by outlying** [WowUp/WowUp#798]
**Describe the bug**
When I use search my sorting is set to show results with top downloads first, but instead of that I see two results from "WowUpHub" first. Phrase used to search "Details"

**To Reproduce**
1. Go to 'Search'
2. Type in "Details" in search field
3. Wrong results

**Expected behavior**
"Details! Damage Meter" should be first

**Screenshots**
![image](https://user-images.githubusercontent.com/2069751/112746985-ce1eae80-8fb2-11eb-892a-b89ef6a35029.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Version:Chome 89, WowUp 2.1.2, OS 11.2.3
 
 TBH Version of what? OS? Chrome? WowUp? this point is not clear, please correct template so it's obvious

**Additional context**
none

**Comment by jliddev** [comment]
Behavior is different in newer versions.

**Comment by outlying** [comment]
@jliddev so the explanation is: it's confusing on purpose

**Comment by jliddev** [comment]
No, the explanation is that this behavior has been changed in newer versions of the app?

**Comment by outlying** [comment]
The answer is evasive in nature, why the behaviour is like this?

This is a very bad UX, not only it's confusing by introducing behaviour that is not found in most of the apps but also there is no communication about why it's behaving like that and that it is to be expected.

Also, it creates distrust, I've only seen two mismatched results but 10 such results may appear so I will not see the thing that actually interests me. Not only can I conclude that WowUp does not have access to a particular addon (for whatever reason), but also that it manipulates the results. 

If you really need to put addons from your own "domain" / "promoted" to the top of your results list, at least communicate it visually.

**Comment by linaori** [comment]
> This is a very bad UX, not only it's confusing by introducing behaviour that is not found in most of the apps but also there is no communication about why it's behaving like that and that it is to be expected.

The only bad UX here is that the top 2 addons don't seem to be related to "Details" as search term. Do you want reasoning for every single default sort order on the planet? In case you don't know yet, you can click the columns and manually sort however you want. 

![image](https://user-images.githubusercontent.com/1754678/112807645-6df24000-9078-11eb-8728-a4ca42942d00.png)

> Also, it creates distrust, I've only seen two mismatched results but 10 such results may appear so I will not see the thing that actually interests me.

If you think this creates mistrust, why haven't you said anything about the Curse search? This one shows the most unrelated addons you can think of when searching. For some addons it gives back 20 other results first while the addon you're searching for has a 100% name match and is all the way below. Note that this isn't something WowUp can easily change because it's how curse gives the results.

> Not only can I conclude that WowUp does not have access to a particular addon (for whatever reason), but also that it manipulates the results.

How did you come to this conclusion? Details is right there in the list. Manipulate the results? _Every_ addon manager does this, it's how sorting works.

> If you really need to put addons from your own "domain" / "promoted" to the top of your results list, at least communicate it visually.

It is communicated visually: 
![image](https://user-images.githubusercontent.com/1754678/112807322-0a681280-9078-11eb-898b-623112b02acd.png)

**Comment by outlying** [comment]
@linaori so simple question: why the app is not sorting results by downloads? Because this is the reason I reported this issue.

I don't understand hostility, I'm pointing out inconsistent behavior created by the way sorting is working in WowUp, I selected to sort by downloads and top results are not top downloaded add-ons.

> The only bad UX here is that the top 2 addons don't seem to be related to "Details" as search term. Do you want reasoning for every single default sort order on the planet? In case you don't know yet, you can click the columns and manually sort however you want.

But I did it, see my screenshots, sorting by downloads is not happening on OS X.

> If you think this creates mistrust, why haven't you said anything about the Curse search?

> Manipulate the results? Every addon manager does this, it's how sorting works.

I don't understand how Curse is relevant to this issue? WowUp clearly adds those two results on top of other results in my case, at least it looks like it. See my screenshot again.

BTW I'm not sure why are you posting screenshots from other versions, this issue report is related to version 2.1.2, run on OS X, mentioned in the first comment and visible on my screenshot.

**Comment by linaori** [comment]
> so simple question: why the app is not sorting results by downloads? Because this is the reason I reported this issue.

Because it doesn't have a sorting by default, and it seems to pick the order of retrieving data. If you wish to sort by downloads, you can sort by downloads. Currently the beta forgets your sorting and that is already reported and will be fixed before 2.2.0 is released: #761

> I don't understand hostility, I'm pointing out inconsistent behavior created by the way sorting is working in WowUp, I selected to sort by downloads and top results are not top downloaded add-ons.

It's not hostility, it's annoyance. As pointed out several times, it already works in a newer version.

> I don't understand how Curse is relevant to this issue? WowUp clearly adds those two results on top of other results in my case, at least it looks like it. See my screenshot again.

It's relevant because you said we're manipulating the results, pointing fingers at us creating mistrust for not showing it the way you expect it to be shown. This while curse is matching your exact description of "creating mistrust" by not sorting addons properly.

> BTW I'm not sure why are you posting screenshots from other versions, this issue report is related to version 2.1.2, run on OS X, mentioned in the first comment and visible on my screenshot.

Because this is the beta, which is further in development than the version you're using. As Zak has mentioned earlier, the behavior in the beta is correct and you'll receive this behavior as soon as 2.2.0 is released.

**Comment by outlying** [comment]
> It's not hostility, it's annoyance. As pointed out several times, it already works in a newer version.

sigh

> Behavior is different in newer versions.

> No, the explanation is that this behavior has been changed in newer versions of the app?

Sorry but it is not the same as for example: "it is fixed in the newer version" or "wait for 2.2.0 it's already fixed"

I'm not here to annoy you but, working in IT for the second decade of my life, I'm used to a bit more precise language, these messages only informed me that sorting would behave differently, literally. But how different?

Anyway, great job, I like this project it's way better than Curse and I'm using it on both Windows and OS X and it works great. I'm here, reporting and writing because I care for projects like that (open source ❤️ ). So, the case closed.
