### ISSUE TITLE
Add standard MacOS Show/Hide options to Application menu

### ISSUE THREAD

**Issue by pepperbc** [WowUp/WowUp#805]
**Is your feature request related to a problem? Please describe.**
Can't show/hide WoWUp easily in MacOS. You can minimize the window, but then you need to maximize it again from the dock when you go back to the app.

**Describe the solution you'd like**
Add the standard MacOS Show/Hide options to the Application menu

**Comment by pepperbc** [comment]
I made an issue and then a pull request (#806) - seems a bit odd now that I've done it. Was I not supposed to make an issue if I was submitting a pull request?

**Comment by micolous** [comment]
@jliddev this issue is still present in the current version of WowUp, and should be reopened. It looks like this issue was closed without the PR being merged.

Unfortunately, it looks like Electron doesn't let you keep the original, localised [application menu](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#App-menu) items, so [the app has to recreate them](https://www.electronjs.org/docs/latest/api/menu#notes-on-macos-application-menu) if it is replacing menus.

There are a couple of other UX issues with WowUp's menus on macOS:

* With this bug fixed, WowUp doesn't need a [menu bar extra](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#Menu-bar-extras) (persistent right-side menu icon) on macOS. If it supported "Hide", then you can always access it again from the Dock, like every other application on macOS.

* With this bug fixed, the "Minimize on Close" option isn't needed, because "Close" and "Quit" are two distinct actions on macOS (most apps keep running until you quit them).

* ["Close" does not belong in the "Window" menu](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#Window-menu):

  > The Window menu doesn’t help people customize the appearance of windows or close them. To customize a window, people use commands in the [View menu](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#View-menu); to close a window, people choose Close in the [File menu](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#File-menu).
