### ISSUE TITLE
Ability to choose the provider for an add-on

### ISSUE THREAD

**Issue by IharBury** [WowUp/WowUp#83]
Some add-ons are hosted on multiple providers and not all the versions are available on all of them. It would be nice to be able which one to use for each such add-on.

Example: Clique currently uses Curse while it also available on WowInterface. Version v90001-0.1.0-beta is only available on WowInterface currently.

**Comment by Lolzen** [comment]
Related but not the same thing: Searching wor Addons seems to favor CF, a setting to select which host is preferred would be nice.
Some older entries i have installed couldn't be detected/found even tho they exist, namely: Tipachu, oGlow, tekability

**Comment by Tetsemi** [comment]
Have to agree, Minimap Button Frame is currently on version 3.1.10h on Curseforge https://www.curseforge.com/wow/addons/minimap-button-frame/files but it's coming up as 3.1.10f on WoWInterface which doesn't work with WoW 8.X.

**Comment by jliddev** [comment]
How would you feel about being able to set the priority of providers.

**Comment by IharBury** [comment]
Priority of providers would also be helpful. It still makes sense to choose different providers for different add-ons however since the desired versions are not necessarily at the same provider for them.

**Comment by Lolzen** [comment]
> How would you feel about being able to set the priority of providers.

perfect for me.

**Comment by SoLoR1** [comment]
Same issue with AddonsSkins, Its on TukIU and Curse, however only curse have beta/alpha versions.

For me, right now, is enough global ability to choose priority, however generally would be better if you can set this by addon. Or rather, set global priority with ability to override it on per addon basis. For example same princip then choosing update channel, you have default option in settings for new addons, however you can override that per addon.

**Comment by nie7321** [comment]
+1 on this, it seems important that users be able to swap the update channel from Curse to something else for their already-installed addons.

**Comment by JVemmer** [comment]
I agree that being able to set it on individual addons would be best. This feature increases in value, the more providers are added, as various authors use various providers differently. Maybe even add prioritization on individual addons?
AddonSkins on TukUI and Curse is a great example, since they have historically had some issues with updating both providers correctly (the TukUI version was 4 versions behind the Curse stable branch at some point), though it usually work fine from TukUI.
Implementation idea: Both globally and for each addon, a user can select one or more providers, and prioritize them; default should stay with "all providers" as it is currently. If one of the providers has a newer version, update from that provider. If two providers has a new version, get the highest prioritized one, unless the lower one has a higher version (to avoid having to update twice). This implementation needs to take into account addons that can only be found at a certain provider, to ensure that the user still gets update notifications (maybe allow users to completely turn off a provider?).

This would allow users to also say "I don't want this addon to be updated from that provider". In combination with a global list that sets this for all addons (superseded by the individual setting of course), this would be a very powerful feature.
For instance a user could disable a provider for all addons that can be found elsewhere, in the completely theoretical event that the company running the provider, begins trying to bully this magnificent manager to stop it using their API.

**Comment by jliddev** [comment]
This concept has been added to the latest 2.0 beta with the ability to switch providers where applicable. this is a complex feature so lets make future tickets assuming thats how it works for now.
