### ISSUE TITLE
Add a sorting priority to addons in warning state

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp#843]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cremor** [comment]
@jliddev Is it by design that addons in warning state are even sorted to the top when they are ignored? Because I think this is very annoying. I have a few very old (but working) addons that match to Curse when I rescan the folder, but that show a warning about being deleted from curse. Previously that didn't bother me since I could just set them to ignored, but now they are always on top if I order by state.
