### ISSUE TITLE
Cannot manually add wow client linux

### ISSUE THREAD

**Issue by attndeficit** [WowUp/WowUp#851]
Updated to latest wowup.io (2.2.0) and in the process it seems to have forgotten where my wow folder is located. It cannot find it on its own and brings me to a rescan screen.  I press Add New to help it out but am unable to actually select my wow folder.  Whenever I try it just opens the next folder instead of accepting my selection (for example, I click on /home/username/games/World of Warcraft/_Classic_/ then I highlight the Interface directory and press open, it opens that directory in my browse window instead of accepting it)

Regardless what I try, it will not locate my wow directory manually.

**Comment by jliddev** [comment]
Try selecting the exe you want to run

**Comment by attndeficit** [comment]
downloaded 2.1.3 and it seems to have auto-detected (or remembered) my wow directory... I was able to update that way.

@jliddev selecting the executable worked with v2.2.0, thank you

**Comment by vkbo** [comment]
This bug still remains and selecting any exe does not work for me with 2.2.1

The issue is as described by @attndeficit, and I cannot select an actual folder to scan, rather any click on "open" just further opens a deeper subfolder. Eventually I end up on a file somewhere deep in the tree that the app rejects as a valid application.
