### ISSUE TITLE
Suggestion: Provider Priority Option

### ISSUE THREAD

**Issue by StormFX** [WowUp/WowUp#867]
Would it be possible to implement a feature that allows users to prioritize providers? Eg, Check GitHub first, then CF, etc.

**Comment by jliddev** [comment]
We talked about this a long time ago internally when we added the ability to turn the providers on and off. Issues arise when you try to reorder things, all providers do not allow the same level of addon matching. For instance if you have one addon that has 2 folders. if you try to match that to TukUI you will only ever match the first folder, leaving the 2nd to be left on ignored since we dont know what it is.

**Comment by StormFX** [comment]
Hm. Fair enough, I suppose. Certainly lends to the idea of getting some consistency across providers. :P
