### ISSUE TITLE
warning is highest status

### ISSUE THREAD

**Issue by beren12** [WowUp/WowUp#885]
Telling me an addon is active but might not work in tbc classic is good in theory, terrible in practice. Please move "Warning" to above ignored or give us the option to allow it. Many addons for classic work fine or mostly fine so far, warning the user is good but doesn't deserve highest prio.

**Comment by linaori** [comment]
> Telling me an addon is active but might not work in tbc classic is good in theory, terrible in practice
Why is it terrible?

> Please move "Warning" to above ignored or give us the option to allow it.
Allow what exactly? The addon is installed.

You can sort the columns to your liking already

**Comment by beren12** [comment]
I have always since the original curse addon manager sorted by last updated with addons that need an update at the top. You can't do this with wowup but I still sorted by status to see quickly what needs an update. Now I have *13* pages of addons with a status of "warning" above the addons that need an update. I get it, they may not work in tbc classic. Give me an option to put "Warning" status down low please

**Comment by beren12** [comment]
> > Telling me an addon is active but might not work in tbc classic is good in theory, terrible in practice
> 
> Why is it terrible?
> 
I have 13 pages of warning status addons to scroll through before the ones that have an update

**Comment by linaori** [comment]
Can you show me what sorting you're using when this happens? In 2.3.0 there was a fix to explicitly move warning addons down:

> Addons with warnings and ignored will be weighted at the bottom again

**Comment by beren12** [comment]
It was 2.3.0 but i have since upgraded to 2.3.1-b2. It’s still at the almost top but at least the update that needs an addon is above it.

**Comment by beren12** [comment]
Nope, I was wrong…

**Comment by beren12** [comment]
<img width="1595" alt="Screen Shot 2021-05-22 at 6 36 34 PM" src="https://user-images.githubusercontent.com/455631/119242577-f1865580-bb2c-11eb-8827-42636a0445fe.png">

**Comment by linaori** [comment]
If the status of Warning vs Update is swapped, it will become "update -> warning -> normal. When this is reversed it would become "normal -> warning -> update" instead of "normal -> update ->warning", which is also not ideal.

Too many people want a different sorting here and we can't cater them all. If the goal is to quickly see update only, would it make sense to make it easier to only see all updates by filtering instead of applying sorting?

**Comment by beren12** [comment]
To me, warning status should be between ignored and up to date. the very old curse used to have a "Recently updated" status as well… Would it be difficult to add a setting for the user to rank the statuses so the user could pick "needs update", then "up to date" then warning then ignored? Honestly "released at" almost works for me but for the bug when new versions are installed and folders rescanned all the ignored become just released.

**Comment by jliddev** [comment]
The reason Warning is at the top is that during a typical day you wont have 10+ addons that have issues. However, during the transition to TBC you're seeing some atypical cases due to provider issues (which is what it's designed for) and author non support. There was a recent change in your #886 ticket that should prevent the released date from appearing as todays date.
