### ISSUE TITLE
Ignored addons get "updated" when rescan done

### ISSUE THREAD

**Issue by beren12** [WowUp/WowUp#886]
Ignored addons should not get "updated" date reset when a rescan is done. Keep it at installed date or something if you dont want to check file modification times please.

**Comment by linaori** [comment]
Do you have an example on how to reproduce this? 

Currently this seems to be working as you describe. I've just done a rescan and the updated at is 3 days ago. The only date that changed is the "released at", which will be corrected as soon as the addon can be matched with a provider again. 

![image](https://user-images.githubusercontent.com/1754678/119231268-4bcce980-bb20-11eb-9fae-18bbf90850c1.png)

**Comment by beren12** [comment]
Sorry I reversed it. "Released at" gets updated. this was an issue since i was sorting by released to see what was needing an update because there were so many addons with a "warning" status at the top.

**Comment by linaori** [comment]
I don't know if it's going to be possible to "remember" the released at date for unmatched addons. The problem is that 1 addon can contain multiple folders, and we don't know which belongs to which because they are unmatched. One possibility would be to not have a released at for unmatched addons as we don't really know the date anyway. Then the sorting can probably be made to sort those as the "oldest".

**Comment by jliddev** [comment]
Added some code to use the last file updated date in the folder of the "unknown" addon instead of just the current date.
