### ISSUE TITLE
Search fails to find random addons

### ISSUE THREAD

**Issue by robmonte** [WowUp/WowUp#887]
**Describe the bug**
When searching for addons, it will fail to find some.

**To Reproduce**
1. Go to 'Get Addons'
2. Click on Search
3. Type in an addon name (e.g. zz_Repair, IgniteTracker, etc)
4. Notice the lack of results
5. Verify the addon exists by going to the site (WowInterface/Curse) and searching for it

**Expected behavior**
The addon should show up in the list

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest

**Comment by jliddev** [comment]
This actually works within the bounds of our system, when you search you're searching via the CF api. The real issue is how curse handles multi toc addons.The search result list is filtered by the wow client you have selected. CF does not currently have valid mechanism to identify addons that use the new multi toc approach, which this does.
![image](https://user-images.githubusercontent.com/20467484/119288243-cde70c00-bc0d-11eb-9770-2fe84e9b7331.png)

![image](https://user-images.githubusercontent.com/20467484/119288371-0686e580-bc0e-11eb-9119-13e155f5709c.png)

**Comment by robmonte** [comment]
@jliddev Another one that fails is MageButtons. That addon is on WowInterface and looks to only have 1 toc file. Is this the same issue as you explained above though?

**Comment by jliddev** [comment]
The search feature does not work with WowInterface. If they have a search api endpoint I am unaware of what it is.
