### ISSUE TITLE
Make automatic updates an option

### ISSUE THREAD

**Issue by syndenbock** [WowUp/WowUp#991]
**Is your feature request related to a problem? Please describe.**
Today I launched WowUp and it automatically downloaded an update, showing a popup message that a new version has been downloaded and I can update. I did not have the option to not update and continue using the current version as the window did not disappear.

**Describe the solution you'd like**
I would love to have an option to not automatically download new updates in the background and instead show a button on the bottom right to manually download on the bottom right. It would also be nice to be able to postpone an update when it was automatically downloaded.

**Comment by jliddev** [comment]
This was done as a way to reduce support issues. Having people stay on old versions when we push necessary fixes is not sustainable.

**Comment by linaori** [comment]
The main support issue was that people didn't update because they didn't notice the update button. A compromise could be that an additional button to close the popup is added, afaik it will still update next startup. The last problem would be that people click the update away, never restart wowup because they leave their PC on, and then never update wowup as a result. Imo this edge-case is small enough though.

The cancel update button could be something like "Update after restarting WowUp" and be less visible to hint people towards the other button.

**Comment by jliddev** [comment]
The app doesnt typically update very often in production so this is probably fine how it is.

**Comment by Debuggernaut** [comment]
Just to go full circle on my complaint here:  https://github.com/WowUp/WowUp/issues/1050

WoWup's forced updates were so important that they had to be crammed down my throat every week even if I was in the middle of something.  Yet somehow, my fork is still working perfectly after _an entire year_ without updates.  Curious.

**Comment by linaori** [comment]
@Debuggernaut we don't release that often. Clearly you have no experience with software updates, so I'm just going to leave it at that. Change your tone and language or you're no longer welcome here.
